[package]
name = "git_to_sticker"
version = "0.1.0"
authors = ["Kolya Opahle <kolyaopahle@gmail.com>", "Milan Proell <milan.proell@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.10.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
reqwest = "0.9.20"
dotenv = "0.14.1"